server:
  port: 2501
logging:
  level:
    root: WARN
    org.springframework: WARN
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    url: jdbc:postgresql://localhost:${refresher_port}/refresher
    username: '${refresher_username}'
    password: '${refresher_password}'
